# Generated by Django 3.1.3 on 2020-11-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
