# Generated by Django 3.1.3 on 2020-11-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201125_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='checkIn',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='checkOut',
            new_name='check_out',
        ),
    ]
